#! /bin/python3


from PyPDF2 import PdfFileWriter, PdfFileReader
import sys


args = sys.argv
print(str(args))


if len(args) < 2:
	raise ValueError("USAGE : <filename> <inputFile> <outputFile> [ <start> <end> ] [ -s <page> ]")


# Pdf location
inputPdf = PdfFileReader(open(args[1], "rb"))

outputPdf = PdfFileWriter()


def addPages (a, b):
	# Range from page a to b
	for i in range (a,b+1):
		outputPdf.addPage(inputPdf.getPage(i))
		
	    # Result Pdf location
		with open(args[2], "wb") as outputStream:
			outputPdf.write(outputStream)
			
			
for i in range (3,len(args),2):
	if args[i] == "-s":
		addPages(int(args[i+1])-1,int(args[i+1])-1)
	else:
		addPages(int(args[i])-1,int(args[i+1])-1)
